site_name: "ROLCH: Regularized Online Learning for Conditional Heteroskedasticity"

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        # docstring_style: "numpy"
        options:
          heading_level: 3
          show_source: false
          show_root_heading: true
          separate_signature: true
          show_signature_annotations: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math

nav:
  - Coordinate Descent : coordinate_descent.md
  - Link Functions : links.md
