site_name: "ROLCH: Regularized Online Learning for Conditional Heteroskedasticity"

nav:
  - Coordinate Descent : coordinate_descent.md
  - Link Functions : links.md
  - Issues [Github] : "https://github.com/simon-hirsch/rolch/issues"
  - Source [Github] : "https://github.com/simon-hirsch/rolch/tree/main"
  - Licence [Github] : "https://github.com/simon-hirsch/rolch/tree/main?tab=MIT-1-ov-file#readme"

theme:
  name: "material"
  features:
    - search.share
    - search.highlight
    - search.suggest

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        # docstring_style: "numpy"
        options:
          heading_level: 3
          show_source: false
          show_root_heading: true
          separate_signature: true
          show_signature_annotations: true
- search

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

