name: Automated Tests
on:
  push:
    branches:    
      - '**'            # matches every branch
      - '!gh-pages'     # excludes gh-pages
  pull_request:
    branches:    
    - '**'              # matches every branch
    - '!gh-pages'       # excludes gh-pages
permissions:
  contents: read
jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        numpy-version: ["1.23", "1.25", "1.26", "2.0.0", "2.1.0"]
        exclude:
          # Old numpy version does not work properly with python > 3.11
          - python-version: "3.12"
            numpy-version: "1.23"
          - python-version: "3.12"
            numpy-version: "1.25"
          - python-version: "3.13"
            numpy-version: "1.23"
          - python-version: "3.13"
            numpy-version: "1.25"
          - python-version: "3.13"
            numpy-version: "1.26"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade setuptools
          pip install numpy==${{ matrix.numpy-version }}
          pip install flake8 pytest
          if [ -f requirements_tests.txt ]; then pip install -r requirements_tests.txt; fi
      - name: Build package
        run: python -m build --wheel
      - name: Install Package
        run: pip install dist/*
      - name: Run tests with pytest
        run: pytest tests

