name: Python application
on:
  push:
    branches: [ "testing_ci" ]
  pull_request:
    branches: [ "testing_ci" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements_tests.txt ]; then pip install -r requirements_tests.txt; fi
      - name: Build package
        run: python -m build
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-package
          path: dist/
      - name: Download and install package
        run: |
          mkdir -p dist
          curl -L ${{ steps.build.outputs.artifacts_url }}/python-package.tar.gz | tar xz -C dist
          pip install dist/*.whl
      - name: Run tests with pytest
        run: pytest test

